sonar.projectKey=taskflow-api
sonar.projectName=TaskFlow API
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.eslint.reportPaths=reports/eslint-report.json

sonar.exclusions=node_modules/**,coverage/**,reports/**,data/**,scripts/**
sonar.coverage.exclusions=tests/**,scripts/**,src/server.js,eslint.config.js
sonar.cpd.exclusions=tests/**
